// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: inc.proto

package inccore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                                                          // Request UUID
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`                                                                                     // Code Block
	Variables     map[string]*Variable   `protobuf:"bytes,3,rep,name=variables,proto3" json:"variables,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Variables (args)
	Config        map[string]string      `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`       // Example: {"memory_limit": "128M"}
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_inc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_inc_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ExecutionRequest) GetVariables() map[string]*Variable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *ExecutionRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ExecutionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Result        *Variable              `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                      // Result of return
	Stdout        string                 `protobuf:"bytes,3,opt,name=stdout,proto3" json:"stdout,omitempty"`                      // Output of print/echo
	Stderr        string                 `protobuf:"bytes,4,opt,name=stderr,proto3" json:"stderr,omitempty"`                      // Errors
	ExitCode      int32                  `protobuf:"varint,5,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"` // 0 = OK, 1 = Error
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionResponse) Reset() {
	*x = ExecutionResponse{}
	mi := &file_inc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResponse) ProtoMessage() {}

func (x *ExecutionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResponse.ProtoReflect.Descriptor instead.
func (*ExecutionResponse) Descriptor() ([]byte, []int) {
	return file_inc_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutionResponse) GetResult() *Variable {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecutionResponse) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *ExecutionResponse) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

func (x *ExecutionResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

// Common IR (Intermediate Representation)
type Variable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Variable_IntVal
	//	*Variable_FloatVal
	//	*Variable_StringVal
	//	*Variable_BoolVal
	//	*Variable_BinaryVal
	//	*Variable_ListVal
	//	*Variable_MapVal
	//	*Variable_NullVal
	Kind          isVariable_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variable) Reset() {
	*x = Variable{}
	mi := &file_inc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variable) ProtoMessage() {}

func (x *Variable) ProtoReflect() protoreflect.Message {
	mi := &file_inc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variable.ProtoReflect.Descriptor instead.
func (*Variable) Descriptor() ([]byte, []int) {
	return file_inc_proto_rawDescGZIP(), []int{2}
}

func (x *Variable) GetKind() isVariable_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Variable) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Variable_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *Variable) GetFloatVal() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Variable_FloatVal); ok {
			return x.FloatVal
		}
	}
	return 0
}

func (x *Variable) GetStringVal() string {
	if x != nil {
		if x, ok := x.Kind.(*Variable_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *Variable) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Kind.(*Variable_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Variable) GetBinaryVal() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Variable_BinaryVal); ok {
			return x.BinaryVal
		}
	}
	return nil
}

func (x *Variable) GetListVal() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Variable_ListVal); ok {
			return x.ListVal
		}
	}
	return nil
}

func (x *Variable) GetMapVal() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Variable_MapVal); ok {
			return x.MapVal
		}
	}
	return nil
}

func (x *Variable) GetNullVal() *NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Variable_NullVal); ok {
			return x.NullVal
		}
	}
	return nil
}

type isVariable_Kind interface {
	isVariable_Kind()
}

type Variable_IntVal struct {
	IntVal int64 `protobuf:"varint,1,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Variable_FloatVal struct {
	FloatVal float64 `protobuf:"fixed64,2,opt,name=float_val,json=floatVal,proto3,oneof"`
}

type Variable_StringVal struct {
	StringVal string `protobuf:"bytes,3,opt,name=string_val,json=stringVal,proto3,oneof"`
}

type Variable_BoolVal struct {
	BoolVal bool `protobuf:"varint,4,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Variable_BinaryVal struct {
	BinaryVal []byte `protobuf:"bytes,5,opt,name=binary_val,json=binaryVal,proto3,oneof"`
}

type Variable_ListVal struct {
	ListVal *ListValue `protobuf:"bytes,6,opt,name=list_val,json=listVal,proto3,oneof"`
}

type Variable_MapVal struct {
	MapVal *MapValue `protobuf:"bytes,7,opt,name=map_val,json=mapVal,proto3,oneof"`
}

type Variable_NullVal struct {
	NullVal *NullValue `protobuf:"bytes,8,opt,name=null_val,json=nullVal,proto3,oneof"`
}

func (*Variable_IntVal) isVariable_Kind() {}

func (*Variable_FloatVal) isVariable_Kind() {}

func (*Variable_StringVal) isVariable_Kind() {}

func (*Variable_BoolVal) isVariable_Kind() {}

func (*Variable_BinaryVal) isVariable_Kind() {}

func (*Variable_ListVal) isVariable_Kind() {}

func (*Variable_MapVal) isVariable_Kind() {}

func (*Variable_NullVal) isVariable_Kind() {}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Variable            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_inc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_inc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_inc_proto_rawDescGZIP(), []int{3}
}

func (x *ListValue) GetValues() []*Variable {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pairs         map[string]*Variable   `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_inc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_inc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_inc_proto_rawDescGZIP(), []int{4}
}

func (x *MapValue) GetPairs() map[string]*Variable {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type NullValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NullValue) Reset() {
	*x = NullValue{}
	mi := &file_inc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NullValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullValue) ProtoMessage() {}

func (x *NullValue) ProtoReflect() protoreflect.Message {
	mi := &file_inc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullValue.ProtoReflect.Descriptor instead.
func (*NullValue) Descriptor() ([]byte, []int) {
	return file_inc_proto_rawDescGZIP(), []int{5}
}

var File_inc_proto protoreflect.FileDescriptor

const file_inc_proto_rawDesc = "" +
	"\n" +
	"\tinc.proto\x12\binc.core\"\xdb\x02\n" +
	"\x10ExecutionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12G\n" +
	"\tvariables\x18\x03 \x03(\v2).inc.core.ExecutionRequest.VariablesEntryR\tvariables\x12>\n" +
	"\x06config\x18\x04 \x03(\v2&.inc.core.ExecutionRequest.ConfigEntryR\x06config\x1aP\n" +
	"\x0eVariablesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.inc.core.VariableR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\x11ExecutionResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12*\n" +
	"\x06result\x18\x02 \x01(\v2\x12.inc.core.VariableR\x06result\x12\x16\n" +
	"\x06stdout\x18\x03 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x04 \x01(\tR\x06stderr\x12\x1b\n" +
	"\texit_code\x18\x05 \x01(\x05R\bexitCode\"\xbe\x02\n" +
	"\bVariable\x12\x19\n" +
	"\aint_val\x18\x01 \x01(\x03H\x00R\x06intVal\x12\x1d\n" +
	"\tfloat_val\x18\x02 \x01(\x01H\x00R\bfloatVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\x03 \x01(\tH\x00R\tstringVal\x12\x1b\n" +
	"\bbool_val\x18\x04 \x01(\bH\x00R\aboolVal\x12\x1f\n" +
	"\n" +
	"binary_val\x18\x05 \x01(\fH\x00R\tbinaryVal\x120\n" +
	"\blist_val\x18\x06 \x01(\v2\x13.inc.core.ListValueH\x00R\alistVal\x12-\n" +
	"\amap_val\x18\a \x01(\v2\x12.inc.core.MapValueH\x00R\x06mapVal\x120\n" +
	"\bnull_val\x18\b \x01(\v2\x13.inc.core.NullValueH\x00R\anullValB\x06\n" +
	"\x04kind\"7\n" +
	"\tListValue\x12*\n" +
	"\x06values\x18\x01 \x03(\v2\x12.inc.core.VariableR\x06values\"\x8d\x01\n" +
	"\bMapValue\x123\n" +
	"\x05pairs\x18\x01 \x03(\v2\x1d.inc.core.MapValue.PairsEntryR\x05pairs\x1aL\n" +
	"\n" +
	"PairsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.inc.core.VariableR\x05value:\x028\x01\"\v\n" +
	"\tNullValue2\x9f\x01\n" +
	"\x06Bridge\x12H\n" +
	"\rCallStateless\x12\x1a.inc.core.ExecutionRequest\x1a\x1b.inc.core.ExecutionResponse\x12K\n" +
	"\fCallStateful\x12\x1a.inc.core.ExecutionRequest\x1a\x1b.inc.core.ExecutionResponse(\x010\x01B1Z/github.com/inc-lang/inc-protocol/gen/go;inccoreb\x06proto3"

var (
	file_inc_proto_rawDescOnce sync.Once
	file_inc_proto_rawDescData []byte
)

func file_inc_proto_rawDescGZIP() []byte {
	file_inc_proto_rawDescOnce.Do(func() {
		file_inc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inc_proto_rawDesc), len(file_inc_proto_rawDesc)))
	})
	return file_inc_proto_rawDescData
}

var file_inc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_inc_proto_goTypes = []any{
	(*ExecutionRequest)(nil),  // 0: inc.core.ExecutionRequest
	(*ExecutionResponse)(nil), // 1: inc.core.ExecutionResponse
	(*Variable)(nil),          // 2: inc.core.Variable
	(*ListValue)(nil),         // 3: inc.core.ListValue
	(*MapValue)(nil),          // 4: inc.core.MapValue
	(*NullValue)(nil),         // 5: inc.core.NullValue
	nil,                       // 6: inc.core.ExecutionRequest.VariablesEntry
	nil,                       // 7: inc.core.ExecutionRequest.ConfigEntry
	nil,                       // 8: inc.core.MapValue.PairsEntry
}
var file_inc_proto_depIdxs = []int32{
	6,  // 0: inc.core.ExecutionRequest.variables:type_name -> inc.core.ExecutionRequest.VariablesEntry
	7,  // 1: inc.core.ExecutionRequest.config:type_name -> inc.core.ExecutionRequest.ConfigEntry
	2,  // 2: inc.core.ExecutionResponse.result:type_name -> inc.core.Variable
	3,  // 3: inc.core.Variable.list_val:type_name -> inc.core.ListValue
	4,  // 4: inc.core.Variable.map_val:type_name -> inc.core.MapValue
	5,  // 5: inc.core.Variable.null_val:type_name -> inc.core.NullValue
	2,  // 6: inc.core.ListValue.values:type_name -> inc.core.Variable
	8,  // 7: inc.core.MapValue.pairs:type_name -> inc.core.MapValue.PairsEntry
	2,  // 8: inc.core.ExecutionRequest.VariablesEntry.value:type_name -> inc.core.Variable
	2,  // 9: inc.core.MapValue.PairsEntry.value:type_name -> inc.core.Variable
	0,  // 10: inc.core.Bridge.CallStateless:input_type -> inc.core.ExecutionRequest
	0,  // 11: inc.core.Bridge.CallStateful:input_type -> inc.core.ExecutionRequest
	1,  // 12: inc.core.Bridge.CallStateless:output_type -> inc.core.ExecutionResponse
	1,  // 13: inc.core.Bridge.CallStateful:output_type -> inc.core.ExecutionResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_inc_proto_init() }
func file_inc_proto_init() {
	if File_inc_proto != nil {
		return
	}
	file_inc_proto_msgTypes[2].OneofWrappers = []any{
		(*Variable_IntVal)(nil),
		(*Variable_FloatVal)(nil),
		(*Variable_StringVal)(nil),
		(*Variable_BoolVal)(nil),
		(*Variable_BinaryVal)(nil),
		(*Variable_ListVal)(nil),
		(*Variable_MapVal)(nil),
		(*Variable_NullVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inc_proto_rawDesc), len(file_inc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inc_proto_goTypes,
		DependencyIndexes: file_inc_proto_depIdxs,
		MessageInfos:      file_inc_proto_msgTypes,
	}.Build()
	File_inc_proto = out.File
	file_inc_proto_goTypes = nil
	file_inc_proto_depIdxs = nil
}
