// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: inc.proto

package inccore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Bridge_CallStateless_FullMethodName = "/inc.core.Bridge/CallStateless"
	Bridge_CallStateful_FullMethodName  = "/inc.core.Bridge/CallStateful"
)

// BridgeClient is the client API for Bridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Bridge provides remote code execution for the INC language runtime.
// Clients send code and variables, and receive execution results including
// stdout/stderr output and a structured return value.
type BridgeClient interface {
	// CallStateless executes a single code block and returns the result.
	// Each request is independent with no shared state between calls.
	CallStateless(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error)
	// CallStateful opens a bidirectional stream for executing multiple code blocks
	// that share state. Variables and definitions from earlier requests in the
	// stream are available to subsequent requests.
	CallStateful(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutionRequest, ExecutionResponse], error)
}

type bridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewBridgeClient(cc grpc.ClientConnInterface) BridgeClient {
	return &bridgeClient{cc}
}

func (c *bridgeClient) CallStateless(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (*ExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutionResponse)
	err := c.cc.Invoke(ctx, Bridge_CallStateless_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bridgeClient) CallStateful(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ExecutionRequest, ExecutionResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Bridge_ServiceDesc.Streams[0], Bridge_CallStateful_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionRequest, ExecutionResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_CallStatefulClient = grpc.BidiStreamingClient[ExecutionRequest, ExecutionResponse]

// BridgeServer is the server API for Bridge service.
// All implementations must embed UnimplementedBridgeServer
// for forward compatibility.
//
// Bridge provides remote code execution for the INC language runtime.
// Clients send code and variables, and receive execution results including
// stdout/stderr output and a structured return value.
type BridgeServer interface {
	// CallStateless executes a single code block and returns the result.
	// Each request is independent with no shared state between calls.
	CallStateless(context.Context, *ExecutionRequest) (*ExecutionResponse, error)
	// CallStateful opens a bidirectional stream for executing multiple code blocks
	// that share state. Variables and definitions from earlier requests in the
	// stream are available to subsequent requests.
	CallStateful(grpc.BidiStreamingServer[ExecutionRequest, ExecutionResponse]) error
	mustEmbedUnimplementedBridgeServer()
}

// UnimplementedBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBridgeServer struct{}

func (UnimplementedBridgeServer) CallStateless(context.Context, *ExecutionRequest) (*ExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CallStateless not implemented")
}
func (UnimplementedBridgeServer) CallStateful(grpc.BidiStreamingServer[ExecutionRequest, ExecutionResponse]) error {
	return status.Error(codes.Unimplemented, "method CallStateful not implemented")
}
func (UnimplementedBridgeServer) mustEmbedUnimplementedBridgeServer() {}
func (UnimplementedBridgeServer) testEmbeddedByValue()                {}

// UnsafeBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BridgeServer will
// result in compilation errors.
type UnsafeBridgeServer interface {
	mustEmbedUnimplementedBridgeServer()
}

func RegisterBridgeServer(s grpc.ServiceRegistrar, srv BridgeServer) {
	// If the following call panics, it indicates UnimplementedBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Bridge_ServiceDesc, srv)
}

func _Bridge_CallStateless_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BridgeServer).CallStateless(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Bridge_CallStateless_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BridgeServer).CallStateless(ctx, req.(*ExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bridge_CallStateful_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BridgeServer).CallStateful(&grpc.GenericServerStream[ExecutionRequest, ExecutionResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Bridge_CallStatefulServer = grpc.BidiStreamingServer[ExecutionRequest, ExecutionResponse]

// Bridge_ServiceDesc is the grpc.ServiceDesc for Bridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inc.core.Bridge",
	HandlerType: (*BridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallStateless",
			Handler:    _Bridge_CallStateless_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CallStateful",
			Handler:       _Bridge_CallStateful_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "inc.proto",
}
